name: nfl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Core numeric / ML (via conda for speed & prebuilt wheels)
  - numpy>=1.26
  - pandas>=2.1
  - scipy>=1.11
  - scikit-learn>=1.3
  - xgboost>=1.7
  - lightgbm>=4.0
  - statsmodels>=0.14
  - networkx>=3.1
  - cvxpy>=1.3
  # Visualization & analysis
  - matplotlib>=3.8
  - seaborn>=0.12
  - plotly>=5.15
  # Dev & testing
  - pytest>=7
  - pytest-asyncio>=0.21
  - black>=22
  - flake8>=5
  - mypy>=0.971
  - pre-commit>=2.20
  # HTTP, scraping, CLI, utils
  - requests>=2.28
  - aiohttp>=3.8
  - beautifulsoup4>=4.11
  - selenium>=4.5
  - typer>=0.9
  - rich>=13
  - click>=8
  - pyyaml>=6.0
  - python-dotenv>=0.20
  - schedule>=1.2
  - tqdm>=4.64
  - python-dateutil>=2.8
  - pytz>=2022.1
  # API & server
  - fastapi>=0.104
  - uvicorn>=0.24
  - websockets>=12
  - redis-py>=5.0
  # Database
  - sqlalchemy>=2.0
  - alembic>=1.8
  - psycopg2>=2.9
  # NLP
  - nltk>=3.8
  - textblob>=0.17.1
  - pip:
      # Pip-only or latest wheels preferred
      - slowapi>=0.1.9
      - python-jose[cryptography]>=3.3.0
      - passlib[bcrypt]>=1.7.4
      - python-multipart>=0.0.6
      - nfl-data-py>=0.3.0
      - bayesian-optimization>=1.4.0
      - optuna>=3.0.0
      - shap>=0.41.0
      - pulp>=2.7.0
