system:
  version: "2.0.0"
  environment: "development"
  
api:
  host: 0.0.0.0
  port: 8000
  workers: 4
  enable: true

database:
  type: sqlite
  url: sqlite:////home/money/CascadeProjects/nfl-betting-analyzer/data/nfl_predictions.db
  path: data/nfl_predictions.db

data:
  directory: data
  update_frequency: daily
  current_season: 2025
  seasons_to_load:
    - 2021
    - 2022
    - 2023
    - 2024
    - 2025

models:
  directory: models
  types:
    - xgboost
    - lightgbm
    - random_forest
  ensemble_method: weighted_average
  retrain_frequency: weekly

features:
  version: v1.0
  batch_size: 100

prediction:
  horizon_days: 7

directories:
  config: config
  logs: logs
  models: models
  data: data

processing:
  max_workers: 4

api_keys:
  news_api_key: null
  sports_api_key: null
  weather_api_key: null
