name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make verify
        run: make verify

      - name: Upload JUnit test report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
          if-no-files-found: warn

      - name: Upload coverage matrices
        uses: actions/upload-artifact@v4
        with:
          name: coverage-matrices
          path: reports/coverage/**
          if-no-files-found: warn

      - name: Upload backtest artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-artifacts
          path: reports/backtests/**
          if-no-files-found: warn
